/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LAB-D-PC12
 */
public class JfrmSupport extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JfrmSupport.class.getName());

    /**
     * Creates new form JfrmSupport
     */
    public JfrmSupport() {
        initComponents();
        this.setSize(800,650);
        this.setTitle("MotherBoard");//titulo
        this.setLocationRelativeTo(null);//localización
        this.setResizable(false);//bloquear la dimensión
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblPieza = new javax.swing.JLabel();
        jlblNomPieza = new javax.swing.JLabel();
        jlblDesc = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 450));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 102, 102));

        jlblPieza.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jlblPieza.setForeground(new java.awt.Color(102, 0, 51));

        jlblNomPieza.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jlblNomPieza.setForeground(new java.awt.Color(153, 0, 51));
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/motherboard.png"))); // NOI18N

        jlblDesc.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jlblNomPieza))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jlblPieza))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jlblDesc)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jlblPieza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblNomPieza)
                .addGap(18, 18, 18)
                .addComponent(jlblDesc)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Imagenes");

        jMenuItem4.setText("PlacaBase");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Procesador");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Ram");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Cooler");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Fuente de Poder");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("MotherBoard");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/motherboard.png")));
        jlblDesc.setText("<html>El circuito principal de un ordenador, Su función principal es conectar<br>y unificar todos los componentes del equipo , permitiendo que se comuniquen entre sí, además<br>de distribuir la energía eléctrica necesaria para su funcionamiento.</html>");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("Procesador");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cpu.png")));
        jlblDesc.setText("<html>Un procesador (CPU) es el componente central de hardware en dispositivos<br>inteligentes y computadoras. Actúa como el cerebro del sistema, encargado de interpretar<br>instrucciones y ejecutar cálculos matemáticos y lógicos. Su función principal es dirigir el<br>funcionamiento del equipo y procesar los datos de todas las aplicaciones.</html>");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("RAM");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ram.png")));
        jlblDesc.setText("<html>Es ,“Memoria de Acceso Aleatorio” en inglés, un tipo de memoria operativa<br>de las computadoras y sistemas informáticos, donde se ejecuta la mayor parte del<br>software, desde el propio sistema operativo hasta el software de aplicación y otros programas<br>semejantes. La función principal es que permite grabar o recuperar información sin necesidad de un orden secuencial<html>");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("Cooler");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cooler.png")));
        jlblDesc.setText("<html>Refiere al conjunto formado por un disipador de metal (que absorbe el<br>calor) y un ventilador (que expulsa ese aire caliente fuera del equipo). Funciona mediante<br>la transferencia, la disipación y flujo de aire <html>");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("Fuente de poder");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fuente.png")));
        jlblDesc.setText("<html>La fuente de poder es el componente que convierte la CA en CC, regulando y<br>distribuyendo la energía hacia cada componente. Su función principal es proteger los componentes de sobrecargas y garantizar que reciban el voltaje correcto para operar.<html>");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JfrmSupport().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblDesc;
    private javax.swing.JLabel jlblNomPieza;
    private javax.swing.JLabel jlblPieza;
    // End of variables declaration//GEN-END:variables
}
