/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
/**
 *
 * @author LAB-D-PC12
 */
public class JfrmSupport extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JfrmSupport.class.getName());

    /**
     * Creates new form JfrmSupport
     */
    public JfrmSupport() {
        initComponents();
        this.setSize(800,650);
        this.setTitle("MotherBoard");//titulo
        this.setLocationRelativeTo(null);//localización
        this.setResizable(false);//bloquear la dimensión
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jlblPieza = new javax.swing.JLabel();
        jlblNomPieza = new javax.swing.JLabel();
        jlblDesc = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 450));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 102, 102));

        jlblPieza.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jlblPieza.setForeground(new java.awt.Color(102, 0, 51));

        jlblNomPieza.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jlblNomPieza.setForeground(new java.awt.Color(153, 0, 51));
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/motherboard.png"))); // NOI18N

        jlblDesc.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jlblNomPieza))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jlblPieza))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jlblDesc)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jlblPieza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblNomPieza)
                .addGap(18, 18, 18)
                .addComponent(jlblDesc)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Componentes del PC");

        jMenuItem4.setText("PlacaBase");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Procesador");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Memoria RAM");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu2.add(jMenuItem6);

        jMenuItem11.setText("Disco Duro (HDD)");
        jMenuItem11.addActionListener(this::jMenuItem11ActionPerformed);
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("Unidad SSD");
        jMenuItem12.addActionListener(this::jMenuItem12ActionPerformed);
        jMenu2.add(jMenuItem12);

        jMenuItem8.setText("Fuente de Poder");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        jMenu2.add(jMenuItem8);

        jMenuItem13.setText("Tarjeta de Video (GPU)");
        jMenuItem13.addActionListener(this::jMenuItem13ActionPerformed);
        jMenu2.add(jMenuItem13);

        jMenuItem14.setText("Tarjeta de Red");
        jMenuItem14.addActionListener(this::jMenuItem14ActionPerformed);
        jMenu2.add(jMenuItem14);

        jMenuItem7.setText("Cooler");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        jMenu2.add(jMenuItem7);

        jMenuItem15.setText("Ventilador del Gabinete");
        jMenuItem15.addActionListener(this::jMenuItem15ActionPerformed);
        jMenu2.add(jMenuItem15);

        jMenuItem16.setText("Tarjeta de Sonido");
        jMenuItem16.addActionListener(this::jMenuItem16ActionPerformed);
        jMenu2.add(jMenuItem16);

        jMenuItem17.setText("Batería CMOS");
        jMenuItem17.addActionListener(this::jMenuItem17ActionPerformed);
        jMenu2.add(jMenuItem17);

        jMenuItem18.setText("Cable SATA");
        jMenuItem18.addActionListener(this::jMenuItem18ActionPerformed);
        jMenu2.add(jMenuItem18);

        jMenuItem19.setText("Cable de Alimentación");
        jMenuItem19.addActionListener(this::jMenuItem19ActionPerformed);
        jMenu2.add(jMenuItem19);

        jMenuItem20.setText("BIOS / UEFI");
        jMenuItem20.addActionListener(this::jMenuItem20ActionPerformed);
        jMenu2.add(jMenuItem20);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Ayuda");

        jMenuItem9.setText("Acerca del programa");
        jMenu5.add(jMenuItem9);

        jMenuItem10.setText("Créditos");
        jMenu5.add(jMenuItem10);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("MotherBoard");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/motherboard.png")));
        jlblDesc.setText("<html>El circuito principal de un ordenador, Su función principal es conectar<br>y unificar todos los componentes del equipo , permitiendo que se comuniquen entre sí, además<br>de distribuir la energía eléctrica necesaria para su funcionamiento.</html>");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("Procesador");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cpu.png")));
        jlblDesc.setText("<html>Un procesador (CPU) es el componente central de hardware en dispositivos<br>inteligentes y computadoras. Actúa como el cerebro del sistema, encargado de interpretar<br>instrucciones y ejecutar cálculos matemáticos y lógicos. Su función principal es dirigir el<br>funcionamiento del equipo y procesar los datos de todas las aplicaciones.</html>");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("RAM");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ram.png")));
        jlblDesc.setText("<html>Es ,“Memoria de Acceso Aleatorio” en inglés, un tipo de memoria operativa<br>de las computadoras y sistemas informáticos, donde se ejecuta la mayor parte del<br>software, desde el propio sistema operativo hasta el software de aplicación y otros programas<br>semejantes. La función principal es que permite grabar o recuperar información sin necesidad de un orden secuencial<html>");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("Cooler");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cooler.png")));
        jlblDesc.setText("<html>Refiere al conjunto formado por un disipador de metal (que absorbe el<br>calor) y un ventilador (que expulsa ese aire caliente fuera del equipo). Funciona mediante<br>la transferencia, la disipación y flujo de aire <html>");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("Fuente de poder");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fuente.png")));
        jlblDesc.setText("<html>La fuente de poder es el componente que convierte la CA en CC, regulando y<br>distribuyendo la energía hacia cada componente. Su función principal es proteger los componentes de sobrecargas y garantizar que reciban el voltaje correcto para operar.<html>");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int msg=JOptionPane.showConfirmDialog(null, "Desea salir del software ;) ");
        if(msg==0)
            System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(null, "Funcionalidad abrir");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(null, "Funcionalidad guardar");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("Tarjeta de Sonido");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tarjetadesonido.jpg")));
        jlblDesc.setText("<html>Concepto: Chip o tarjeta de expansión dedicada a procesar las señales de audio del sistema.<br>Función principal: Traducir los datos digitales de la computadora en sonido analógico para altavoces/auriculares, y viceversa para micrófonos.<html>");
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("Batería CMOS");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BateríaCMOS.jpg")));
        jlblDesc.setText("<html>Concepto: Pequeña pila de botón (usualmente el modelo CR2032) ubicada en la tarjeta madre.<br>Función principal: Mantener energizado el chip de la BIOS/UEFI para que no se borren la hora, la fecha y las configuraciones de hardware al apagar la PC.<html>");
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("Disco Duro SSD/HDD");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Discoduro.jpg")));
        jlblDesc.setText("<html>Concepto: Es el dispositivo de almacenamiento masivo y permanente de la computadora.<br>Función principal: Guardar de forma definitiva el sistema operativo, los programas, juegos y todos tus archivos personales, incluso cuando la PC está apagada.<html>");
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("Unidad SSD");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SSD.jpg")));
        jlblDesc.setText("<html>Concepto: Dispositivo de almacenamiento de estado sólido basado en memoria flash, sin partes móviles.<br>Función principal: Guardar datos de forma permanente a velocidades muy altas, permitiendo que el sistema y los programas arranquen casi al instante.<html>");
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("Tarjeta de Video (GPU)");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tarjetavideo.jpg")));
        jlblDesc.setText("<html>Concepto: Componente especializado en el procesamiento de datos visuales y gráficos.<br>Función principal: Procesar y renderizar imágenes, videos y juegos para mostrarlos directamente en la pantalla o monitor.<html>");
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("Tarjeta de Red");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tarjeta-de-red.png")));
        jlblDesc.setText("<html>Concepto: Dispositivo de conectividad (integrado o expansión) por cable (Ethernet) o inalámbrico (Wi-Fi).<br>Función principal: Permitir que la computadora se conecte a una red local y a Internet para transmitir y recibir datos<html>");
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("Ventilador del Gabinete");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventiladorgab.jpg")));
        jlblDesc.setText("<html>Concepto: Ventilador interno instalado en las rejillas del chasis de la computadora.<br>Función principal: Generar un flujo constante de aire fresco hacia adentro y expulsar el aire caliente hacia afuera de la PC.<html>");
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("Cable SATA");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CableSATA.jpg")));
        jlblDesc.setText("<html>Concepto: Cable de datos plano e interno que conecta dispositivos de almacenamiento a la placa base.<br>Función principal: Transferir información a alta velocidad entre la tarjeta madre y los discos duros (HDD) o unidades SSD.<html>");
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("Cable de Alimentación");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CableAlimentacion.jpg")));
        jlblDesc.setText("<html>Concepto: Cable eléctrico externo de grueso calibre que va desde el enchufe de la pared hasta la fuente de poder.<br>Función principal: Transportar de forma segura la corriente alterna desde la toma eléctrica del hogar hacia la fuente de la PC.<html>");
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        jlblPieza.setText("");
        jlblPieza.setText("BIOS/UEFI");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BIOS.jpg")));
        jlblDesc.setText("<html>Concepto: Sistema de software básico e interno grabado en un chip de memoria en la tarjeta madre.<br>Función principal: Realizar el chequeo inicial del hardware (POST) al encender la computadora e iniciar la carga del sistema operativo.<html>");
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JfrmSupport().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblDesc;
    private javax.swing.JLabel jlblNomPieza;
    private javax.swing.JLabel jlblPieza;
    // End of variables declaration//GEN-END:variables
}
